variables:
  CONTAINER_IMAGE: "docker-host.ccuvpndom.com:5000/i2-kiss-api"

image: python:3.13.1-bookworm

stages:
  - build
  - docker_build
  - docker_deploy

build_job:
  stage: build
  script:
    - echo "Installing uv..."
    - pip install uv
    - echo "Building the project..."
    - python -m venv venv #


docker_build_and_push:
  stage: docker_build
  image: docker:27.4.0
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - echo "Build Docker Image"
    - ls -la
    - pwd
    - docker info
    - docker build --no-cache -t my-i2-kiss-api-container .
    - docker tag my-i2-kiss-api-container $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker image push $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_TAG'


docker_deploy_to_server:
  stage: docker_deploy
  image: docker:27.4.0
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - apk add --no-cache rsync
    - echo "Deploying to production server..."
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    #- ls -la ~/.ssh
    #- cat ~/.ssh/id_rsa
    #:ad0a4ff7 
    - ssh -o StrictHostKeyChecking=no docker@192.168.70.5 "
        bash -c '
          pwd
          ls -la
          rm -rf i2-kiss-api 
          mkdir i2-kiss-api
        '
      "
    - sed -i "s|__DOCKER_TAG__|$CI_COMMIT_SHORT_SHA|g" docker-compose.yml
    - rsync -e "ssh -o StrictHostKeyChecking=no" -avz ./docker-compose.yml docker@192.168.70.5:~/i2-kiss-api
    - rsync -e "ssh -o StrictHostKeyChecking=no" -avz ./.env docker@192.168.70.5:~/i2-kiss-api/.env
    
  

