version: '3.9'

networks:
  web:
  internal:

services:
  kiss-api:
    env_file: .env
    container_name: kiss-api
    image: 'kiss-api-image'
    restart: unless-stopped
    ports:
      - '8085:80'
    environment:
      USERS: '${USERS}'
      SECRET_KEY: '${SECRET_KEY}'
      KISS_IRIS_PORT: '${KISS_IRIS_PORT}'
      KISS_IRIS_IP: '${KISS_IRIS_IP}'
      KISS_USERNAME: '${KISS_USERNAME}'
      KISS_PASSWORD: '${KISS_PASSWORD}'
      KISS_SCHEMA: '${KISS_SCHEMA}'
      CONNECTION_SSH_JUMP_PRIVATE_KEY: '${CONNECTION_SSH_JUMP_PRIVATE_KEY}'
      CONNECTION_SSH_JUMP_USER: '${CONNECTION_SSH_JUMP_USER}'
      CONNECTION_SSH_JUMP_HOST: '${CONNECTION_SSH_JUMP_HOST}'
      USE_OLD_CACHE_DRIVER: '${USE_OLD_CACHE_DRIVER}'
    volumes:
      - '/home/datalab/.ssh/:/cert'
    networks:
      - internal